services:
  front-web:
    build:
      context: ./build
      dockerfile: nginx.Dockerfile
    volumes:
      - ./front/dist:/www/web
    ports:
      - $PORT_FRONT:80

  front:
    image: node:latest
    volumes:
      - ./front:/app
    working_dir: /app
  
  directus:
    image: directus/directus
    ports:
      - $PORT_DIRECTUS:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file: directus.env

  gateway:
    image: canals/php:8.3
    ports:
      - $PORT_GATEWAY:80
    volumes:
      - ./gateway/public:/var/www/html
      - ./gateway:/var/www
      - ./sql:/var/sql
    working_dir: /var/www

  auth:
    image: canals/php:8.3
    ports:
      - $PORT_AUTH:80
    volumes:
      - ./auth/public:/var/www/html
      - ./auth:/var/www
      - ./sql:/var/sql
    working_dir: /var/www
    env_file: 
      - db.env
      - auth.env

  game:
    image: canals/php:8.3
    ports:
      - $PORT_GAME:80
    volumes:
      - ./game/public:/var/www/html
      - ./game:/var/www
      - ./sql:/var/sql
    working_dir: /var/www
    env_file: 
      - db.env
      - ./amqp.env
      - ./back.env

  auth.db:
    image: 'postgres:latest'
    # ports:
    #   - $PORT_AUTH_DB:5432
    volumes:
      - ./sql:/var/sql'
    env_file: db.env

  game.db:
    image: 'postgres:latest'
    # ports:
    #   - $PORT_GAME_DB:5432
    volumes:
      - ./sql:/var/sql'
    env_file: db.env

  queue:
    image: rabbitmq:4-management
    ports:
      - $PORT_QUEUE:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=toto
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 8s
      timeout: 30s
      retries: 3

  mailer:
    image: canals/php:8.3
    volumes:
      - ./mailer:/var/www/html
    working_dir: /var/www/html
    env_file: 
      - ./mailer.env
      - ./amqp.env
    command: php mailer.php
    depends_on:
      queue:
        condition: service_healthy

  mailcatcher:
    build:
      context: ./build
      dockerfile: mailcatcher.Dockerfile
    ports:
      - $PORT_MAILCATCHER:1080
      - 1025:1025
